# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
loader_version=0.16.14
parchment_version=[VERSIONED]
# Mod Properties
mod_version=2.4.0
maven_group=me.pajic
archives_base_name=simple_smithing_overhaul
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=[VERSIONED]
mixinconstraints_version=1.1.0
mixson_version=v1.4.0
modmenu_version=[VERSIONED]
owo_version=[VERSIONED]
emi_version=[VERSIONED]
ed_version=[VERSIONED]
rearm_version=[VERSIONED]
taxfreelevels_version=[VERSIONED]
cloth_version=[VERSIONED]