org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.caching=true
loader_version=0.17.3
parchment_version=[VERSIONED]
mod_version=2.5.6
maven_group=me.pajic
archives_base_name=simple_smithing_overhaul
fabric_version=[VERSIONED]
mixinconstraints_version=1.1.0
mixson_version=v1.4.0
modmenu_version=[VERSIONED]
owo_version=[VERSIONED]
emi_version=[VERSIONED]
ed_version=[VERSIONED]
rearm_version=[VERSIONED]
taxfreelevels_version=[VERSIONED]
cloth_version=[VERSIONED]
enchdesc_version=[VERSIONED]
kaleido_version=0.3.3+1.3.2