org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=simple_smithing_overhaul
mod.name=Simple Smithing Overhaul
mod.group=me.pajic
mod.version=2.7.0
mod.channel_tag=
mod.authors=pajic
mod.contributors=Lufurrius, Moonkey
mod.license=MIT
mod.description=Portable item repair, enchantment upgrading, anvil improvements and more
mod.sources_url=https://github.com/pajicadvance/simple-smithing-overhaul
mod.homepage_url=https://modrinth.com/mod/simple-smithing-overhaul
mod.issues_url=https://github.com/pajicadvance/simple-smithing-overhaul/issues
mod.discord_url=https://discord.gg/5RkzS66zWb

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.fzzy_config=[VERSIONED]
deps.mixson=[VERSIONED]

deps.ed=[VERSIONED]
deps.tfl=[VERSIONED]

publish.modrinth=U5TJjZc3
publish.curseforge=1179744
publish.github=false
